package mutate

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

func TestCandidateFilesUsesRecentGitLogAndFilters(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "go.mod", "module example.com/sample\n\ngo 1.23\n")
	writeFile(t, dir, "old/old.go", "package old\n\nfunc Old() {}\n")
	writeFile(t, dir, "old/old_test.go", "package old\n\nimport \"testing\"\n\nfunc TestOld(t *testing.T) {}\n")
	writeFile(t, dir, "calc/calc.go", "package calc\n\nfunc Add(a, b int) int { return a + b }\n")
	writeFile(t, dir, "calc/calc_test.go", "package calc\n\nimport \"testing\"\n\nfunc TestAdd(t *testing.T) {}\n")
	writeFile(t, dir, "calc/generated.go", "// Code generated by test. DO NOT EDIT.\npackage calc\n\nfunc Generated() {}\n")
	runGit(t, dir, "init")
	runGit(t, dir, "add", ".")
	runGit(t, dir, "commit", "-m", "initial")
	writeFile(t, dir, "calc/calc.go", "package calc\n\nfunc Add(a, b int) int { return a + b + 0 }\n")
	runGit(t, dir, "add", ".")
	runGit(t, dir, "commit", "-m", "touch calc")

	files, err := CandidateFiles(context.Background(), dir, 10)
	if err != nil {
		t.Fatalf("CandidateFiles returned error: %v", err)
	}
	want := []string{"calc/calc.go", "old/old.go"}
	if len(files) != len(want) {
		t.Fatalf("files = %#v, want %#v", files, want)
	}
	for i := range want {
		if files[i] != want[i] {
			t.Fatalf("files = %#v, want %#v", files, want)
		}
	}
}

func TestCandidateFilesFallsBackToWalk(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "pkg/pkg.go", "package pkg\n\nfunc Value() int { return 1 }\n")
	writeFile(t, dir, "pkg/pkg_test.go", "package pkg\n\nimport \"testing\"\n\nfunc TestValue(t *testing.T) {}\n")

	files, err := CandidateFiles(context.Background(), dir, 10)
	if err != nil {
		t.Fatalf("CandidateFiles returned error: %v", err)
	}
	if len(files) != 1 || files[0] != "pkg/pkg.go" {
		t.Fatalf("files = %#v, want pkg/pkg.go", files)
	}
}

func writeFile(t *testing.T, root, rel, content string) {
	t.Helper()
	full := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatalf("create parent dir: %v", err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatalf("write file: %v", err)
	}
}

func runGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GIT_AUTHOR_NAME=CodeDojo", "GIT_AUTHOR_EMAIL=codedojo@example.com", "GIT_COMMITTER_NAME=CodeDojo", "GIT_COMMITTER_EMAIL=codedojo@example.com")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %v failed: %v\n%s", args, err, out)
	}
}
